clean:
	rm -rf inversion.* inversion_prior.* logs/* output.log testdir Clumping_Test_* Sensitivity_Test_* PDA_* submit.rtm.inversion.modex.sh.e* submit.rtm.inversion.modex.sh.o* *.log *.pdf *.qsub.log.txt
