#' USDA texture code conversion table
#'
#' @export
texture_codes <- tibble::tribble(
  # NOTE: This is missing some classes
  ~texture_code, ~ed_texture_id,
  "HPM", 12,
  "FSL", 3,
  "CB-FSL", 3,
  "CBV-FSL", 3,
  "CVB-LS", 2,
  "L", 5,
  "SL", 3,
  "UWB", 13,
  "ST-SIL", 4,
  "CB-SIL", 4,
  "SIL", 4,
  "CN-S", 1,
  "WB", 13,
  "LS", 2,
  "S", 1,
  "MUCK", 12,
  "CN-L", 5,
  "BR", 13,
  "CN-SIL", 4,
  "CNV-SIL", 4,
  "CNX-SIL", 4,
  "SPM", 12,
  "GR-SL", 3,
  "CNV-SL", 3,
  "FLX-SL", 3,
  "STX-L", 5,
  "STV-SL", 3,
  "GR-COS", 1,
  "SR- S GRV-COS", 1,
  "GR-S", 1,
  "GR-LS", 2,
  "MPM", 12,
  "S LS", 2,
  "COS", 1,
  "LFS", 2,
  "FS", 1,
  "GR-FSL", 3,
  "C", 11,
  "CS", 16,
  "SR- VFS SI", 1,
  "PEAT", 12,
  "MPT", 12
)
